name: ci

env:
  BINARY_NAME: bucketblocker
  GO_VERSION: 1.19

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - ts/nt/ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: go test ./...
