name: ci

env:
  GO_VERSION: 1.22.1

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: go list -f '{{.Dir}}/...' -m | xargs go test

  build-bucket-blocker:
    name: Build bucket-blocker
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Run build
        uses: ./.github/actions/build
        with:
          APP: bucket-blocker
          GO_VERSION: ${{ env.GO_VERSION }}

  build-ingress-inquisition:
    name: Build ingress-inquisition
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Run build
        uses: ./.github/actions/build
        with:
          APP: ingress-inquisition
          GO_VERSION: ${{ env.GO_VERSION }}

  enforce-bucket-blocker:
    name: Enforce bucket-blocker spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Lint naming
        run: ./script/dash-lint.sh bucket-blocker

  enforce-ingress-inquisition:
    name: Enforce ingress-inquisition spelling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Lint naming
        run: ./script/dash-lint.sh ingress-inquisition

  release:
    name: Create GitHub release
    permissions:
      contents: write
      packages: write
      issues: write
    needs:
      [
        build-ingress-inquisition,
        build-bucket-blocker,
        enforce-bucket-blocker,
        enforce-ingress-inquisition,
      ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          # See https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md
          node-version: "20.14.0"

      - name: Fetch build
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: artifact-bucket-blocker
          path: bucket-blocker/release

      - name: Fetch build
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
        with:
          name: artifact-ingress-inquisition
          path: ingress-inquisition/release

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
